spring:
  application:
    name: spring-cloud-feign-client
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true